apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: mysql-db-svc
  namespace: my
  labels:
    app: my-app
spec:
  selector:
    app: my-db
  ports:
  - protocol: TCP
    port: 3306
  type: NodePort