apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-peristent-volume
  namespace: my
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql"
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-peristent-volume-claim
  namespace: my
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: "mysql-peristent-volume"
  # storageClassName: "local-storage-class"