apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: my
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: mynodeapp:1.2
        name: my-app
        ports:
        - name: my-app
          containerPort: 3000
        resources:
          limits:
            cpu: 0.1