version: '3'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: test
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
  web:
    build: .
    depends_on:
     - db
    ports:
     - "3000:3000"